name: Build Apps

on:
  pull_request:
    branches:
      - main
      - main-*

jobs:
  build-apps:
    name: Build apps
    
    # This ensures we have access to android signing key
    # which is required to build the apps.
    environment: Android Service Runtime Release
    
    runs-on: self-hosted
    container:
      image: ubuntu:24.04
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: android-service-runtime
            features: ""

          - name: android-service-runtime
            features: system_settings

          - name: example-client-app
            features: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          apt-get update
          apt-get install -y sudo build-essential curl

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-24.05
          enable_kvm: false

      - uses: cachix/cachix-action@v15
        env:
          USER: root
        with:
          name: holochain-ci

      - name: setup Android signing
        run: |
          cd apps/${{ matrix.build.name }}/src-tauri/gen/android
          base64 -d <<< "${{ secrets.ANDROID_KEY_BASE64 }}" > $RUNNER_TEMP/keystore.jks
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" > key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> key.properties
          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> key.properties
          echo "storePassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> key.properties

      - name: Build app ${{ matrix.build.name }} ${{ matrix.build.features }}
        run: |
          nix develop --no-update-lock-file --command bash -c "pnpm install && pnpm run build:${{ matrix.build.name }}  --features ${{ matrix.build.features }} --target x86_64 --apk"

  build-tauri-plugins:
    name: Build tauri plugins
    runs-on: self-hosted
    container:
      image: ubuntu:24.04
    strategy:
      fail-fast: false
      matrix:
        name:
          - tauri-plugin-service
          - tauri-plugin-client
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          apt-get update
          apt-get install -y sudo build-essential curl

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-24.05
          enable_kvm: false

      - uses: cachix/cachix-action@v15
        env:
          USER: root
        with:
          name: holochain-ci

      - name: Build tauri plugin ${{ matrix.name }}
        run: |
          nix develop --no-update-lock-file --command bash -c "pnpm install && pnpm run build:single-target:${{ matrix.name }} x86_64-linux-android"